# Generated by Django 2.0 on 2018-12-23 00:02

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0014_auto_20181223_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_type', models.CharField(default='', max_length=20, verbose_name='物品类别')),
                ('address', models.CharField(default='', max_length=50, verbose_name='预约地址')),
                ('phone_num', models.CharField(default='', max_length=15, verbose_name='手机号')),
                ('remark', models.CharField(default='', max_length=200, verbose_name='备注')),
                ('money', models.IntegerField(default=0, verbose_name='单次回收积分')),
                ('bag_num', models.CharField(default='', max_length=30, verbose_name='袋子编号')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='预约创建日期')),
                ('create_time', models.TimeField(auto_now_add=True, verbose_name='预约创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(choices=[(0, '已预约'), (1, '已绑袋'), (2, '回收完成 ')], default=0, verbose_name='回收状态')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='学校')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '回收预约',
                'verbose_name_plural': '回收预约',
                'db_table': 'dn_recovery_appoint',
            },
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=30, verbose_name='袋子编号')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '回收袋信息',
                'verbose_name_plural': '回收袋信息',
                'db_table': 'dn_recovery_bag',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='环保知识介绍')),
                ('view_num', models.IntegerField(default=0, verbose_name='全国浏览量')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '回收环保知识介绍',
                'verbose_name_plural': '回收环保知识介绍',
                'db_table': 'dn_recovery_introduction',
            },
        ),
        migrations.CreateModel(
            name='MyRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0, verbose_name='回收次数')),
                ('money', models.IntegerField(default=0, verbose_name='回收总积分')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='学校')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '回收个人排名信息',
                'verbose_name_plural': '回收个人排名信息',
                'db_table': 'dn_recovery_rank',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='物品名称')),
                ('unit', models.CharField(default='', max_length=5, verbose_name='物品单位')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='物品价格')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '回收物品价格',
                'verbose_name_plural': '回收物品价格',
                'db_table': 'dn_recovery_price',
            },
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField(default='', verbose_name='预约学校宿舍提示信息')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='学校')),
            ],
            options={
                'verbose_name': '回收学校提示信息',
                'verbose_name_plural': '回收学校提示信息',
                'db_table': 'dn_recovery_tips',
            },
        ),
    ]
