# Generated by Django 2.0 on 2018-12-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='重量小数'),
        ),
        migrations.AddField(
            model_name='appoint',
            name='worker_num',
            field=models.CharField(default='', max_length=30, verbose_name='称重工作人员编号'),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='money',
            field=models.IntegerField(default=0, verbose_name='单次回收积分整数'),
        ),
    ]
