# Generated by Django 2.0 on 2018-12-04 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activites_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('content', models.TextField(default='', max_length=200, verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'dn_activites_comment',
            },
        ),
        migrations.RemoveField(
            model_name='activites',
            name='comment',
        ),
        migrations.AddField(
            model_name='activites_comment',
            name='activites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Activites', verbose_name='校园活动'),
        ),
        migrations.AddField(
            model_name='activites_comment',
            name='commentator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='评论者'),
        ),
    ]
