# Generated by Django 2.0 on 2018-12-05 05:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_auto_20181203_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='文章标题')),
                ('content', tinymce.models.HTMLField(verbose_name='文章内容')),
                ('editor', models.CharField(default='', max_length=10, verbose_name='编辑人员')),
                ('author', models.CharField(default='', max_length=10, verbose_name='作者')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间')),
                ('view_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='学校')),
            ],
            options={
                'verbose_name': '文章推荐',
                'verbose_name_plural': '文章推荐',
                'db_table': 'dn_article',
            },
        ),
        migrations.CreateModel(
            name='Article_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('content', models.TextField(default='', max_length=200, verbose_name='评论内容')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='文章推荐')),
                ('commentator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='评论者')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'dn_article_comment',
            },
        ),
    ]
