# Generated by Django 2.0 on 2018-12-04 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='文章标题')),
                ('content', tinymce.models.HTMLField(verbose_name='文章内容')),
                ('editor', models.CharField(default='', max_length=10, verbose_name='编辑人员')),
                ('author', models.CharField(default='', max_length=10, verbose_name='作者')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间')),
                ('view_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='culture.Comment', verbose_name='评论')),
            ],
            options={
                'verbose_name': '文章推荐',
                'verbose_name_plural': '文章推荐',
                'db_table': 'dn_article',
            },
        ),
    ]
