# Generated by Django 2.0 on 2018-12-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('article', '0002_auto_20181204_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='学校'),
        ),
    ]
