# Generated by Django 2.0 on 2018-12-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181205_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='list_img',
            field=models.ImageField(default='', upload_to='article/%Y/%m', verbose_name='文章标题'),
        ),
    ]
