# Generated by Django 2.0 on 2018-12-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20181206_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='comment_date',
            new_name='comment_datetime',
        ),
        migrations.AddField(
            model_name='article',
            name='is_show',
            field=models.SmallIntegerField(choices=[(0, '不显示'), (1, '显示')], default=1, verbose_name='显示'),
        ),
        migrations.AlterField(
            model_name='article',
            name='list_img',
            field=models.ImageField(default='', upload_to='article/%Y/%m', verbose_name='文章头像'),
        ),
    ]
