# Generated by Django 2.0 on 2019-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20181228_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_all_school',
            field=models.SmallIntegerField(choices=[(0, '不显示'), (1, '显示')], default=0, verbose_name='同步全国'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_original',
            field=models.SmallIntegerField(choices=[(0, '不显示'), (1, '显示')], default=0, verbose_name='原创'),
        ),
    ]
