# Generated by Django 2.0 on 2018-12-05 06:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_auto_20181205_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='活动标题')),
                ('big_img', models.ImageField(default='', upload_to='activity/%Y/%m', verbose_name='首页轮播图')),
                ('small_img', models.ImageField(default='', upload_to='activity/%Y/%m', verbose_name='列表图')),
                ('introduction', models.TextField(default='', max_length=200, verbose_name='活动简介')),
                ('content', tinymce.models.HTMLField(verbose_name='活动内容')),
                ('editor', models.CharField(default='', max_length=10, verbose_name='编辑人员')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间')),
                ('view_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='学校')),
            ],
            options={
                'verbose_name': '校园活动',
                'verbose_name_plural': '校园活动',
                'db_table': 'dn_Activity',
            },
        ),
        migrations.CreateModel(
            name='Activity_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('content', models.TextField(default='', max_length=200, verbose_name='评论内容')),
                ('Activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='校园活动')),
                ('commentator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='评论者')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'dn_Activity_comment',
            },
        ),
    ]
