# Generated by Django 2.0 on 2018-12-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181205_1616'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity_comment',
            new_name='ActivityComment',
        ),
        migrations.AlterModelTable(
            name='activity',
            table='dn_activity',
        ),
        migrations.AlterModelTable(
            name='activitycomment',
            table='dn_activity_comment',
        ),
    ]
