# Generated by Django 2.0 on 2018-12-05 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20181205_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='publish_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='发表时间'),
        ),
    ]
