# Generated by Django 2.0 on 2018-12-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20181205_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_first',
            field=models.SmallIntegerField(choices=[(0, '未置顶'), (1, '置顶')], default=0, verbose_name='置顶'),
        ),
    ]
