# Generated by Django 2.0 on 2018-12-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20181205_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='host_unit',
            field=models.CharField(default='官方', max_length=30, verbose_name='主办方'),
        ),
    ]
