# Generated by Django 2.0 on 2018-12-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activity_host_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_show',
            field=models.SmallIntegerField(choices=[(0, '不显示'), (1, '显示')], default=1, verbose_name='显示'),
        ),
    ]
