# Generated by Django 2.0 on 2018-12-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20181206_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitycomment',
            old_name='Activity',
            new_name='activity',
        ),
    ]
