# Generated by Django 2.0 on 2018-12-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20181206_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycomment',
            name='comment_date',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
    ]
