# Generated by Django 2.0 on 2019-01-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20181228_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycomment',
            name='comment_datetime',
        ),
    ]
