# Generated by Django 2.0 on 2019-02-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_activitycomment_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='editor',
            field=models.CharField(default='', max_length=30, verbose_name='编辑人员'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='host_unit',
            field=models.CharField(default='官方', max_length=50, verbose_name='主办方'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='活动标题'),
        ),
        migrations.AlterField(
            model_name='activitycomment',
            name='content',
            field=models.CharField(default='', max_length=300, verbose_name='评论内容'),
        ),
    ]
