# Generated by Django 2.0 on 2018-12-04 05:57

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='公告标题')),
                ('content', tinymce.models.HTMLField(verbose_name='公告内容')),
                ('editor', models.CharField(default='', max_length=10, verbose_name='编辑人员')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间')),
                ('view_num', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
        ),
    ]
