# Generated by Django 2.0 on 2018-12-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '校园公告', 'verbose_name_plural': '校园公告'},
        ),
        migrations.AlterModelTable(
            name='notice',
            table='dn_notice',
        ),
    ]
