# Generated by Django 2.0 on 2019-01-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20181205_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='sort_num',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
