# Generated by Django 2.0 on 2018-12-04 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='发表时间'),
        ),
    ]
