# Generated by Django 2.0 on 2019-01-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_sort_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_show',
            field=models.SmallIntegerField(choices=[(0, '显示'), (1, '不显示')], default=0, verbose_name='是否显示'),
        ),
    ]
