# Generated by Django 2.0 on 2018-12-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='find',
            new_name='moment',
        ),
    ]
