# Generated by Django 2.0 on 2018-12-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0002_auto_20181210_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='voice_time',
            field=models.CharField(default='', max_length=20, verbose_name='音频时长'),
        ),
    ]
