# Generated by Django 2.0 on 2018-12-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0003_voice_voice_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='local_video_img',
            field=models.FileField(default='', upload_to='moment_video/%Y/%m/%d', verbose_name='本地视频缩略图'),
        ),
        migrations.AddField(
            model_name='video',
            name='qiniu_video_img',
            field=models.CharField(default='', max_length=100, verbose_name='七牛云视频缩略图'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_size',
            field=models.CharField(default='', max_length=20, verbose_name='视频大小'),
        ),
    ]
