# Generated by Django 2.0 on 2018-12-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0004_auto_20181210_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='local_video_img',
            field=models.ImageField(default='', upload_to='moment_video/%Y/%m/%d', verbose_name='本地视频缩略图'),
        ),
    ]
