# Generated by Django 2.0 on 2018-12-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20181212_1827'),
        ('moment', '0006_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate_datetime', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moment.Comment', verbose_name='关联评论id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='关联用户id')),
            ],
            options={
                'verbose_name': '评论·点赞',
                'verbose_name_plural': '评论·点赞',
                'db_table': 'dn_comment_good',
            },
        ),
    ]
