# Generated by Django 2.0 on 2018-12-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0007_commentgood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentgood',
            options={'verbose_name': '发现·评论点赞', 'verbose_name_plural': '发现·评论点赞'},
        ),
    ]
