# Generated by Django 2.0 on 2018-12-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0009_auto_20181214_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moment.ReplyComment', verbose_name='自关联的父级'),
        ),
    ]
