# Generated by Django 2.0 on 2018-12-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0011_report_publish_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='is_global',
            field=models.SmallIntegerField(choices=[(0, '不同步'), (1, '同步全国')], default=1, verbose_name='是否同步全国'),
        ),
    ]
