# Generated by Django 2.0 on 2018-12-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0013_auto_20181226_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentgood',
            options={'verbose_name': '发现·评论·点赞', 'verbose_name_plural': '发现·评论·点赞'},
        ),
        migrations.AlterModelOptions(
            name='moment',
            options={'verbose_name': '发现·发布内容', 'verbose_name_plural': '发现·发布内容'},
        ),
        migrations.AlterModelOptions(
            name='replycomment',
            options={'verbose_name': '发现·评论·回复', 'verbose_name_plural': '发现·评论·回复'},
        ),
    ]
