# Generated by Django 2.0 on 2019-02-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0015_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=300, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='commentvideo',
            name='video_size',
            field=models.CharField(default='', max_length=30, verbose_name='视频大小'),
        ),
        migrations.AlterField(
            model_name='commentvoice',
            name='voice_time',
            field=models.CharField(default='', max_length=30, verbose_name='音频时长'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_size',
            field=models.CharField(default='', max_length=30, verbose_name='视频大小'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_time',
            field=models.CharField(default='', max_length=30, verbose_name='音频时长'),
        ),
    ]
