# Generated by Django 2.0 on 2019-03-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20190224_1244'),
        ('moment', '0016_auto_20190225_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefuseFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('moment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moment.Moment', verbose_name='发现id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '发现·屏蔽说说',
                'verbose_name_plural': '发现·屏蔽说说',
                'db_table': 'dn_moment_refuse_find',
            },
        ),
        migrations.CreateModel(
            name='RefuseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_id', models.IntegerField(default=0, verbose_name='他的id')),
                ('publish_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('my_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='我的id')),
            ],
            options={
                'verbose_name': '发现·屏蔽用户',
                'verbose_name_plural': '发现·屏蔽用户',
                'db_table': 'dn_moment_refuse_user',
            },
        ),
    ]
