# Generated by Django 2.0 on 2018-12-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_show',
            field=models.SmallIntegerField(choices=[(0, '未入驻'), (1, '已入驻')], default=0, verbose_name='入驻'),
        ),
    ]
