# Generated by Django 2.0 on 2018-12-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_school_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='入驻'),
        ),
    ]
