# Generated by Django 2.0 on 2018-12-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181202_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_enter',
            field=models.SmallIntegerField(choices=[(0, '未入驻'), (1, '已入驻')], default=0, verbose_name='入驻'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='是否显示'),
        ),
    ]
