# Generated by Django 2.0 on 2018-12-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181202_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school_id',
            new_name='school',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_image',
            field=models.ImageField(default='', upload_to='user/%Y/%m', verbose_name='用户头像'),
        ),
    ]
