# Generated by Django 2.0 on 2018-12-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181203_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_num',
            field=models.CharField(max_length=10, verbose_name='等号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='college_name',
            field=models.CharField(default='', max_length=30, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_num',
            field=models.CharField(max_length=100, verbose_name='设备号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(default='', max_length=30, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_name',
            field=models.CharField(default='', max_length=30, verbose_name='学校'),
        ),
    ]
