# Generated by Django 2.0 on 2018-12-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181205_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_num',
            field=models.CharField(default='', max_length=10, verbose_name='等号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_qn_url',
            field=models.CharField(default='', max_length=100, verbose_name='七牛头像地址'),
        ),
    ]
