# Generated by Django 2.0 on 2018-12-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181205_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_id', models.IntegerField(default=0, verbose_name='我的关注用户id')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('create_time', models.TimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '关注',
                'verbose_name_plural': '关注',
                'db_table': 'dn_user_follow',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_num',
            field=models.CharField(default='', max_length=20, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='user',
            name='stu_num',
            field=models.CharField(default='', max_length=30, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='user',
            name='stu_password',
            field=models.CharField(default='', max_length=30, verbose_name='学号密码'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
    ]
