# Generated by Django 2.0 on 2018-12-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20181210_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='是否显示在APP'),
        ),
    ]
