# Generated by Django 2.0 on 2018-12-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20181220_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(default='', max_length=15, verbose_name='手机号'),
        ),
    ]
