# Generated by Django 2.0 on 2018-12-23 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20181223_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(default='', max_length=30, verbose_name='学校名称')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='学校')),
            ],
            options={
                'verbose_name': '学校模块',
                'verbose_name_plural': '学校模块',
                'db_table': 'dn_school_module',
            },
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': '用户关注', 'verbose_name_plural': '用户关注'},
        ),
        migrations.AddField(
            model_name='user',
            name='device_model',
            field=models.CharField(default='', max_length=100, verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_name',
            field=models.CharField(default='', max_length=100, verbose_name='设备名称'),
        ),
        migrations.AddField(
            model_name='user',
            name='operator',
            field=models.CharField(default='', max_length=100, verbose_name='设备运营商名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_num',
            field=models.CharField(default='', max_length=100, verbose_name='设备唯一标识'),
        ),
    ]
