# Generated by Django 2.0 on 2018-12-23 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20181223_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionmodule',
            old_name='user',
            new_name='school',
        ),
    ]
