# Generated by Django 2.0 on 2018-12-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20181225_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_delete',
            field=models.SmallIntegerField(choices=[(0, '关注中...'), (1, '已取消关注')], default=0, verbose_name='是否取消关注'),
        ),
    ]
