# Generated by Django 2.0 on 2018-12-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_aboutwe_aboutwecomment_recoveryperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryperson',
            name='is_use',
            field=models.SmallIntegerField(choices=[(0, '正在使用中...'), (1, '暂停使用')], default=0, verbose_name='账号状态是否开放'),
        ),
    ]
