# Generated by Django 2.0 on 2018-12-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20181228_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutwecomment',
            options={'verbose_name': '关于我们·评论', 'verbose_name_plural': '关于我们·评论'},
        ),
        migrations.AlterModelOptions(
            name='recoveryperson',
            options={'verbose_name': '工作人员·回收', 'verbose_name_plural': '工作人员·回收'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校列表', 'verbose_name_plural': '学校列表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户账号资料', 'verbose_name_plural': '用户账号资料'},
        ),
        migrations.AddField(
            model_name='aboutwecomment',
            name='is_delete',
            field=models.SmallIntegerField(choices=[(0, '显示'), (1, '已删除')], default=0, verbose_name='是否显示'),
        ),
    ]
