# Generated by Django 2.0 on 2019-01-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20181228_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(default='', max_length=15, verbose_name='手机号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('log_ip', models.CharField(default='', max_length=30, verbose_name='登录IP')),
                ('device_num', models.CharField(default='', max_length=50, verbose_name='设备唯一标识')),
                ('device_model', models.CharField(default='', max_length=50, verbose_name='设备型号')),
                ('device_name', models.CharField(default='', max_length=50, verbose_name='设备名称')),
                ('operator', models.CharField(default='', max_length=50, verbose_name='设备运营商名称')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '用户·登录',
                'verbose_name_plural': '用户·登录',
                'db_table': 'dn_user_login',
            },
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': '用户·关注', 'verbose_name_plural': '用户·关注'},
        ),
        migrations.AlterModelOptions(
            name='recoveryperson',
            options={'verbose_name': '用户·回收人员', 'verbose_name_plural': '用户·回收人员'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户·账号资料', 'verbose_name_plural': '用户·账号资料'},
        ),
        migrations.AddField(
            model_name='user',
            name='comment_total',
            field=models.IntegerField(default=0, verbose_name='获评论总数'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_total',
            field=models.IntegerField(default=0, verbose_name='获关注总数'),
        ),
        migrations.AddField(
            model_name='user',
            name='fans_total',
            field=models.IntegerField(default=0, verbose_name='获粉丝总数'),
        ),
        migrations.AddField(
            model_name='user',
            name='good_total',
            field=models.IntegerField(default=0, verbose_name='获喜欢总数'),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_ip',
            field=models.CharField(default='', max_length=30, verbose_name='注册IP'),
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
    ]
