# Generated by Django 2.0 on 2019-01-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20190117_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutwecomment',
            name='about_we',
        ),
    ]
