# Generated by Django 2.0 on 2019-01-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_remove_aboutwecomment_about_we'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutwe',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
    ]
