# Generated by Django 2.0 on 2019-01-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_cj_kb'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='connection_type',
            field=models.CharField(default='', max_length=30, verbose_name='网络连接类型'),
        ),
        migrations.AddField(
            model_name='login',
            name='jail_break',
            field=models.CharField(default='', max_length=10, verbose_name='设备是否越狱'),
        ),
        migrations.AddField(
            model_name='login',
            name='screen_height',
            field=models.CharField(default='', max_length=30, verbose_name='屏幕分辨率高'),
        ),
        migrations.AddField(
            model_name='login',
            name='screen_width',
            field=models.CharField(default='', max_length=30, verbose_name='屏幕分辨率宽'),
        ),
        migrations.AddField(
            model_name='login',
            name='system_type',
            field=models.CharField(default='', max_length=30, verbose_name='手机系统类型'),
        ),
        migrations.AddField(
            model_name='login',
            name='system_version',
            field=models.CharField(default='', max_length=30, verbose_name='手机平台系统版本'),
        ),
        migrations.AddField(
            model_name='user',
            name='channel',
            field=models.CharField(default='', max_length=50, verbose_name='下载渠道来源'),
        ),
        migrations.AddField(
            model_name='user',
            name='system_type',
            field=models.CharField(default='', max_length=30, verbose_name='手机系统类型'),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_model',
            field=models.CharField(default='', max_length=50, verbose_name='设备型号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_name',
            field=models.CharField(default='', max_length=30, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_num',
            field=models.CharField(default='', max_length=50, verbose_name='设备唯一标识'),
        ),
        migrations.AlterField(
            model_name='user',
            name='operator',
            field=models.CharField(default='', max_length=30, verbose_name='设备运营商名称'),
        ),
    ]
