# Generated by Django 2.0 on 2019-01-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20190124_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='channel',
            field=models.CharField(default='', max_length=50, verbose_name='下载渠道来源'),
        ),
    ]
