# Generated by Django 2.0 on 2019-02-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_login_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='find_total',
            field=models.IntegerField(default=0, verbose_name='说说总数'),
        ),
        migrations.AddField(
            model_name='user',
            name='help_total',
            field=models.IntegerField(default=0, verbose_name='help总数'),
        ),
    ]
