# Generated by Django 2.0 on 2018-12-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0012_auto_20181212_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=500, verbose_name='help内容')),
                ('publish_date', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('publish_time', models.TimeField(auto_now_add=True, verbose_name='发布时间')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('report_num', models.IntegerField(default=0, verbose_name='举报数')),
                ('is_online', models.SmallIntegerField(choices=[(0, '线上'), (1, '线下')], default=0, verbose_name='线上线下')),
                ('is_all_school', models.SmallIntegerField(choices=[(0, '本校'), (1, '所有学校')], default=0, verbose_name='是否所有学校可见')),
                ('is_show', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已经删除')], default=0, verbose_name='是否取消')),
                ('status', models.SmallIntegerField(choices=[(0, '未接单'), (1, '已接单'), (2, '交易完成 ')], default=0, verbose_name='交易状态')),
                ('finish_datetime', models.DateTimeField(auto_now=True, verbose_name='完成时间')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='学校')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发布人')),
            ],
            options={
                'verbose_name': 'help·发布内容',
                'verbose_name_plural': 'help·发布内容',
                'db_table': 'dn_help',
            },
        ),
        migrations.CreateModel(
            name='HelpComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100, verbose_name='评论内容')),
                ('comment_date', models.DateField(auto_now_add=True, verbose_name='评论日期')),
                ('comment_time', models.TimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_show', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已经删除')], default=0, verbose_name='是否删除')),
                ('myhelp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.Help', verbose_name='Help_id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'help·评论',
                'verbose_name_plural': 'help·评论',
                'db_table': 'dn_help_comment',
            },
        ),
        migrations.CreateModel(
            name='HelpImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiniu_img', models.CharField(default='', max_length=100, verbose_name='七牛云地址')),
                ('local_img', models.ImageField(default='', upload_to='myhelp/%Y/%m/%d', verbose_name='本地地址')),
                ('publish_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('myhelp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.Help', verbose_name='Help_id')),
            ],
            options={
                'verbose_name': 'help·图片',
                'verbose_name_plural': 'help·图片',
                'db_table': 'dn_help_image',
            },
        ),
        migrations.CreateModel(
            name='HelpOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='接单日期')),
                ('order_time', models.TimeField(auto_now_add=True, verbose_name='接单时间')),
                ('is_you', models.SmallIntegerField(choices=[(0, '是你'), (1, '不是你')], default=0, verbose_name='是不是你去完成')),
                ('myhelp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.Help', verbose_name='Help id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='接单者')),
            ],
            options={
                'verbose_name': 'help·接单',
                'verbose_name_plural': 'help·接单',
                'db_table': 'dn_help_order',
            },
        ),
        migrations.CreateModel(
            name='HelpReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myhelp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.Help', verbose_name='Help_id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': 'help·举报',
                'verbose_name_plural': 'help·举报',
                'db_table': 'dn_help_report',
            },
        ),
    ]
