# Generated by Django 2.0 on 2018-12-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_follow_is_delete'),
        ('myhelp', '0002_helpreport_publish_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCommentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiniu_img', models.CharField(default='', max_length=100, verbose_name='七牛云地址')),
                ('local_img', models.ImageField(default='', upload_to='myhelp_comment_img/%Y/%m/%d', verbose_name='本地地址')),
                ('publish_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'Help·评论·图片',
                'verbose_name_plural': 'Help·评论·图片',
                'db_table': 'dn_help_comment_image',
            },
        ),
        migrations.CreateModel(
            name='HelpReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=120, verbose_name='评论内容')),
                ('comment_date', models.DateField(auto_now_add=True, verbose_name='回复评论日期')),
                ('comment_time', models.TimeField(auto_now_add=True, verbose_name='回复评论时间')),
            ],
            options={
                'verbose_name': 'Help·回复评论',
                'verbose_name_plural': 'Help·回复评论',
                'db_table': 'dn_help_comment_reply',
            },
        ),
        migrations.AddField(
            model_name='help',
            name='view_num',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='helpcomment',
            name='content',
            field=models.CharField(default='', max_length=300, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='helpcomment',
            name='is_show',
            field=models.SmallIntegerField(choices=[(0, '未删除'), (1, '已经删除')], default=0, verbose_name='是否显示'),
        ),
        migrations.AddField(
            model_name='helpreplycomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.HelpComment', verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='helpreplycomment',
            name='myhelp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.Help', verbose_name='Help'),
        ),
        migrations.AddField(
            model_name='helpreplycomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.HelpReplyComment', verbose_name='自关联的父级'),
        ),
        migrations.AddField(
            model_name='helpreplycomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='helpcommentimage',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.HelpComment', verbose_name='评论id'),
        ),
    ]
