# Generated by Django 2.0 on 2018-12-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhelp', '0004_helpcommentvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpcommentvoice',
            name='comment',
        ),
        migrations.DeleteModel(
            name='HelpCommentVoice',
        ),
    ]
