# Generated by Django 2.0 on 2018-12-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhelp', '0005_auto_20181226_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpreplycomment',
            options={'verbose_name': 'Help·评论·回复', 'verbose_name_plural': 'Help·评论·回复'},
        ),
    ]
