# Generated by Django 2.0 on 2019-02-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhelp', '0006_auto_20181228_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未接单'), (1, '已接'), (2, '交易完成 ')], default=0, verbose_name='交易状态'),
        ),
    ]
