# Generated by Django 2.0 on 2019-03-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20190224_1244'),
        ('myhelp', '0008_auto_20190225_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefuseHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('myhelp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.Help', verbose_name='help_id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': 'help·屏蔽',
                'verbose_name_plural': 'help·屏蔽',
                'db_table': 'dn_help_refuse',
            },
        ),
        migrations.AlterField(
            model_name='helpcomment',
            name='myhelp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.Help', verbose_name='help_id'),
        ),
        migrations.AlterField(
            model_name='helpimage',
            name='myhelp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.Help', verbose_name='help_id'),
        ),
        migrations.AlterField(
            model_name='helporder',
            name='myhelp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.Help', verbose_name='help_id'),
        ),
        migrations.AlterField(
            model_name='helpreplycomment',
            name='myhelp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.Help', verbose_name='help_id'),
        ),
        migrations.AlterField(
            model_name='helpreport',
            name='myhelp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhelp.Help', verbose_name='help_id'),
        ),
    ]
