# Generated by Django 2.0 on 2018-12-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_auto_20181205_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=300, verbose_name='内容')),
                ('view_num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('good_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('create_time', models.TimeField(auto_now_add=True, verbose_name='时间')),
                ('is_first', models.SmallIntegerField(choices=[(0, '未置顶'), (1, '置顶')], default=0, verbose_name='置顶')),
                ('is_type', models.SmallIntegerField(choices=[(0, '丢失'), (1, '捡到'), (2, '已领取'), (3, '已找到')], default=1, verbose_name='类型')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='发布者')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School', verbose_name='学校')),
            ],
        ),
        migrations.CreateModel(
            name='LoseImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiniu_img', models.CharField(default='', max_length=100, verbose_name='七牛地址')),
                ('local_img', models.ImageField(default='', upload_to='lose/%Y/%m/%d', verbose_name='本地地址')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='日期时间')),
                ('lose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lose.Lose', verbose_name='失物招领')),
            ],
        ),
    ]
