# Generated by Django 2.0 on 2018-12-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lose', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lose',
            options={'verbose_name': '失物招领发布', 'verbose_name_plural': '失物招领发布'},
        ),
        migrations.AlterModelOptions(
            name='loseimg',
            options={'verbose_name': '失物招领图片', 'verbose_name_plural': '失物招领图片'},
        ),
        migrations.AlterModelTable(
            name='lose',
            table='dn_lose',
        ),
        migrations.AlterModelTable(
            name='loseimg',
            table='dn_lose_img',
        ),
    ]
