# Generated by Django 2.0 on 2018-12-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lose', '0002_auto_20181208_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='lose',
            name='time_stamp',
            field=models.CharField(default='', max_length=30, verbose_name='时间戳'),
        ),
    ]
