# Generated by Django 2.0 on 2018-12-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20181225_1635'),
        ('lose', '0003_lose_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100, verbose_name='评论内容')),
                ('comment_date', models.DateField(auto_now_add=True, verbose_name='评论日期')),
                ('comment_time', models.TimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_show', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已经删除')], default=0, verbose_name='是否删除')),
                ('lose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lose.Lose', verbose_name='失物')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '失物招领评论',
                'verbose_name_plural': '失物招领评论',
                'db_table': 'dn_lose_comment',
            },
        ),
        migrations.CreateModel(
            name='LoseReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100, verbose_name='评论内容')),
                ('comment_date', models.DateField(auto_now_add=True, verbose_name='回复评论日期')),
                ('comment_time', models.TimeField(auto_now_add=True, verbose_name='回复评论时间')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lose.LoseComment', verbose_name='评论')),
                ('lose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lose.Lose', verbose_name='失物')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lose.LoseReplyComment', verbose_name='自关联的父级')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '失物招领回复评论',
                'verbose_name_plural': '失物招领回复评论',
                'db_table': 'dn_lose_comment_reply',
            },
        ),
    ]
