# Generated by Django 2.0 on 2018-12-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lose', '0004_losecomment_losereplycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lose',
            name='time_stamp',
        ),
    ]
