# Generated by Django 2.0 on 2018-12-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lose', '0005_remove_lose_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lose',
            name='is_show',
            field=models.SmallIntegerField(choices=[(0, '未删除'), (1, '已经删除')], default=0, verbose_name='是否删除'),
        ),
    ]
