# Generated by Django 2.0 on 2019-02-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lose', '0007_auto_20181228_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='losecomment',
            name='content',
            field=models.CharField(default='', max_length=300, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='losereplycomment',
            name='content',
            field=models.CharField(default='', max_length=300, verbose_name='评论内容'),
        ),
    ]
