# Generated by Django 2.0 on 2019-03-19 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20190224_1244'),
        ('lose', '0008_auto_20190225_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('lose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lose.Lose', verbose_name='失物id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '失物招领·举报',
                'verbose_name_plural': '失物招领·举报',
                'db_table': 'dn_lose_report',
            },
        ),
        migrations.CreateModel(
            name='RefuseLose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('lose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lose.Lose', verbose_name='失物id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '失物招领·屏蔽',
                'verbose_name_plural': '失物招领·屏蔽',
                'db_table': 'dn_lose_refuse',
            },
        ),
    ]
