# Generated by Django 2.0 on 2018-12-04 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('activities', '0002_auto_20181204_1549'),
        ('article', '0002_auto_20181204_1549'),
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('content', models.TextField(default='', max_length=200, verbose_name='评论内容')),
                ('commentator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='评论者')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'dn_culture_comment',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentator',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='culture_comment',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='culture.Culture', verbose_name='校园文化'),
        ),
    ]
