# Generated by Django 2.0 on 2018-12-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181205_1616'),
        ('culture', '0002_auto_20181205_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Culture_comment',
            new_name='CultureComment',
        ),
    ]
