# Generated by Django 2.0 on 2018-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0004_auto_20181205_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default='2018-12-05 21:33:21', verbose_name='发表时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='culture',
            name='publish_date',
            field=models.DateField(auto_now=True, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='culturecomment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
    ]
