# Generated by Django 2.0 on 2018-12-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0006_auto_20181206_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturecomment',
            options={'verbose_name': '校园文化·评论', 'verbose_name_plural': '校园文化·评论'},
        ),
    ]
