# Generated by Django 2.0 on 2019-01-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0008_culture_comment_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturecomment',
            name='is_show',
            field=models.SmallIntegerField(choices=[(0, '显示'), (1, '不显示')], default=0, verbose_name='是否显示'),
        ),
    ]
