# Generated by Django 2.0 on 2018-12-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondimg',
            name='local_img',
            field=models.ImageField(default='', upload_to='second/%Y/%m/%d', verbose_name='本地地址'),
        ),
    ]
