# Generated by Django 2.0 on 2018-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_auto_20181209_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='second',
            name='report_num',
            field=models.IntegerField(default=0, verbose_name='举报数'),
        ),
    ]
