# Generated by Django 2.0 on 2018-12-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20181225_1635'),
        ('second', '0003_second_report_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100, verbose_name='评论内容')),
                ('comment_date', models.DateField(auto_now_add=True, verbose_name='评论日期')),
                ('comment_time', models.TimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_show', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已经删除')], default=0, verbose_name='是否删除')),
                ('replay_num', models.IntegerField(default=0, verbose_name='评论回复数量')),
            ],
            options={
                'verbose_name': '校园二手评论',
                'verbose_name_plural': '校园二手评论',
                'db_table': 'dn_second_comment',
            },
        ),
        migrations.CreateModel(
            name='SecondReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100, verbose_name='评论内容')),
                ('comment_date', models.DateField(auto_now_add=True, verbose_name='回复评论日期')),
                ('comment_time', models.TimeField(auto_now_add=True, verbose_name='回复评论时间')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second.SecondComment', verbose_name='评论')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second.SecondReplyComment', verbose_name='自关联的父级')),
            ],
            options={
                'verbose_name': '校园二手回复评论',
                'verbose_name_plural': '校园二手回复评论',
                'db_table': 'dn_second_comment_reply',
            },
        ),
        migrations.AddField(
            model_name='second',
            name='is_show',
            field=models.SmallIntegerField(choices=[(0, '未删除'), (1, '已经删除')], default=0, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='second',
            name='want_num',
            field=models.IntegerField(default=0, verbose_name='想要人数'),
        ),
        migrations.AddField(
            model_name='secondreplycomment',
            name='second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second.Second', verbose_name='二手'),
        ),
        migrations.AddField(
            model_name='secondreplycomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='secondcomment',
            name='second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second.Second', verbose_name='二手'),
        ),
        migrations.AddField(
            model_name='secondcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
    ]
