# Generated by Django 2.0 on 2018-12-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0004_auto_20181225_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='second',
            options={'verbose_name': '校园二手·发布', 'verbose_name_plural': '校园二手·发布'},
        ),
        migrations.AlterModelOptions(
            name='secondcomment',
            options={'verbose_name': '校园二手·评论', 'verbose_name_plural': '校园二手·评论'},
        ),
        migrations.AlterModelOptions(
            name='secondimg',
            options={'verbose_name': '校园二手·图片', 'verbose_name_plural': '校园二手·图片'},
        ),
        migrations.AlterModelOptions(
            name='secondreplycomment',
            options={'verbose_name': '校园二手·评论回复', 'verbose_name_plural': '校园二手·评论回复'},
        ),
    ]
